set(command "/usr/bin/cmake;-P;/mnt/afstuderen/arrow/cpp/build-support/utf8proc_ep-prefix/src/utf8proc_ep-stamp/download-utf8proc_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/bin/cmake;-P;/mnt/afstuderen/arrow/cpp/build-support/utf8proc_ep-prefix/src/utf8proc_ep-stamp/verify-utf8proc_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/usr/bin/cmake;-P;/mnt/afstuderen/arrow/cpp/build-support/utf8proc_ep-prefix/src/utf8proc_ep-stamp/extract-utf8proc_ep.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
